version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Ruby
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for DotNet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"